// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkoSjXWJzYWIlsaduZzmncNjfH6L94iFI',
    appId: '1:908973422755:android:8e2b2fd035ba0238b02716',
    messagingSenderId: '908973422755',
    projectId: 'tsctestproject-43097',
    storageBucket: 'tsctestproject-43097.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARI43mmGcksgJd11WFaRGReOaBtV68ye0',
    appId: '1:908973422755:ios:603e90809fe11afcb02716',
    messagingSenderId: '908973422755',
    projectId: 'tsctestproject-43097',
    storageBucket: 'tsctestproject-43097.appspot.com',
    iosBundleId: 'com.example.tscApp',
  );
}
